
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: aaa
            client-secret: aaa
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  application:
    name: vendora-identity
  main:
    allow-bean-definition-overriding: true
